package fr.iglee42.evolvedmekanism.datagen;

import fr.iglee42.evolvedmekanism.EvolvedMekanism;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

public class EMLangProvider extends LanguageProvider {

    public EMLangProvider(PackOutput output) {
        super(output, EvolvedMekanism.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("constants.evolvedmekanism.mod_name", "Evolved Mekanism");
        add("advancements.evolvedmekanism.apt.description", "This thing doesn't seem safe at all");
        add("advancements.evolvedmekanism.apt.title", "Antimatter Protomolecular Transmutation?");
        add("block.evolvedmekanism.alloyer", "Alloyer");
        add("block.evolvedmekanism.chemixer", "Chemixer");
        add("block.evolvedmekanism.thermalizer", "Thermalizer");
        add("block.evolvedmekanism.solidification_chamber", "Solidification Chamber");
        add("block.mekanism.basic_alloying_factory", "Basic Alloying Factory");
        add("block.mekanism.basic_chemixing_factory", "Basic Chemixing Factory");
        add("block.mekanism.advanced_alloying_factory", "Advanced Alloying Factory");
        add("block.mekanism.advanced_chemixing_factory", "Advanced Chemixing Factory");
        add("block.evolvedmekanism.advanced_personal_barrel", "Advanced Personal Barrel");
        add("block.evolvedmekanism.advanced_personal_chest", "Advanced Personal Chest");
        add("block.mekanism.elite_alloying_factory", "Elite Alloying Factory");
        add("block.mekanism.elite_chemixing_factory", "Elite Chemixing Factory");
        add("block.evolvedmekanism.elite_personal_barrel", "Elite Personal Barrel");
        add("block.evolvedmekanism.elite_personal_chest", "Elite Personal Chest");
        add("block.mekanism.ultimate_alloying_factory", "Ultimate Alloying Factory");
        add("block.mekanism.ultimate_chemixing_factory", "Ultimate Chemixing Factory");
        add("block.evolvedmekanism.ultimate_personal_barrel", "Ultimate Personal Barrel");
        add("block.evolvedmekanism.ultimate_personal_chest", "Ultimate Personal Chest");
        add("block.evolvedmekanism.overclocked_bin", "Overclocked Bin");
        add("block.evolvedmekanism.overclocked_chemical_tank", "Overclocked Chemical Tank");
        add("block.evolvedmekanism.overclocked_combining_factory", "Overclocked Combining Factory");
        add("block.evolvedmekanism.overclocked_compressing_factory", "Overclocked Compressing Factory");
        add("block.evolvedmekanism.overclocked_crushing_factory", "Overclocked Crushing Factory");
        add("block.evolvedmekanism.overclocked_energy_cube", "Overclocked Energy Cube");
        add("block.evolvedmekanism.overclocked_enriching_factory", "Overclocked Enriching Factory");
        add("block.evolvedmekanism.overclocked_fluid_tank", "Overclocked Fluid Tank");
        add("block.evolvedmekanism.overclocked_induction_cell", "Overclocked Induction Cell");
        add("block.evolvedmekanism.overclocked_induction_provider", "Overclocked Induction Provider");
        add("block.evolvedmekanism.overclocked_infusing_factory", "Overclocked Infusing Factory");
        add("block.evolvedmekanism.overclocked_injecting_factory", "Overclocked Injecting Factory");
        add("block.evolvedmekanism.overclocked_logistical_transporter", "Overclocked Logistical Transporter");
        add("block.evolvedmekanism.overclocked_mechanical_pipe", "Overclocked Mechanical Pipe");
        add("block.evolvedmekanism.overclocked_pressurized_tube", "Overclocked Pressurized Tube");
        add("block.evolvedmekanism.overclocked_purifying_factory", "Overclocked Purifying Factory");
        add("block.evolvedmekanism.overclocked_sawing_factory", "Overclocked Sawing Factory");
        add("block.evolvedmekanism.overclocked_smelting_factory", "Overclocked Smelting Factory");
        add("block.evolvedmekanism.overclocked_alloying_factory", "Overclocked Alloying Factory");
        add("block.evolvedmekanism.overclocked_chemixing_factory", "Overclocked Chemixing Factory");
        add("block.evolvedmekanism.overclocked_thermodynamic_conductor", "Overclocked Thermodynamic Conductor");
        add("block.evolvedmekanism.overclocked_universal_cable", "Overclocked Universal Cable");
        add("block.evolvedmekanism.overclocked_personal_barrel", "Overclocked Personal Barrel");
        add("block.evolvedmekanism.overclocked_personal_chest", "Overclocked Personal Chest");
        add("block.evolvedmekanism.quantum_bin", "Quantum Bin");
        add("block.evolvedmekanism.quantum_chemical_tank", "Quantum Chemical Tank");
        add("block.evolvedmekanism.quantum_combining_factory", "Quantum Combining Factory");
        add("block.evolvedmekanism.quantum_compressing_factory", "Quantum Compressing Factory");
        add("block.evolvedmekanism.quantum_crushing_factory", "Quantum Crushing Factory");
        add("block.evolvedmekanism.quantum_energy_cube", "Quantum Energy Cube");
        add("block.evolvedmekanism.quantum_enriching_factory", "Quantum Enriching Factory");
        add("block.evolvedmekanism.quantum_fluid_tank", "Quantum Fluid Tank");
        add("block.evolvedmekanism.quantum_induction_cell", "Quantum Induction Cell");
        add("block.evolvedmekanism.quantum_induction_provider", "Quantum Induction Provider");
        add("block.evolvedmekanism.quantum_infusing_factory", "Quantum Infusing Factory");
        add("block.evolvedmekanism.quantum_injecting_factory", "Quantum Injecting Factory");
        add("block.evolvedmekanism.quantum_logistical_transporter", "Quantum Logistical Transporter");
        add("block.evolvedmekanism.quantum_mechanical_pipe", "Quantum Mechanical Pipe");
        add("block.evolvedmekanism.quantum_pressurized_tube", "Quantum Pressurized Tube");
        add("block.evolvedmekanism.quantum_purifying_factory", "Quantum Purifying Factory");
        add("block.evolvedmekanism.quantum_sawing_factory", "Quantum Sawing Factory");
        add("block.evolvedmekanism.quantum_smelting_factory", "Quantum Smelting Factory");
        add("block.evolvedmekanism.quantum_alloying_factory", "Quantum Alloying Factory");
        add("block.evolvedmekanism.quantum_chemixing_factory", "Quantum Chemixing Factory");
        add("block.evolvedmekanism.quantum_thermodynamic_conductor", "Quantum Thermodynamic Conductor");
        add("block.evolvedmekanism.quantum_universal_cable", "Quantum Universal Cable");
        add("block.evolvedmekanism.quantum_personal_barrel", "Quantum Personal Barrel");
        add("block.evolvedmekanism.quantum_personal_chest", "Quantum Personal Chest");
        add("block.evolvedmekanism.dense_bin", "Dense Bin");
        add("block.evolvedmekanism.dense_chemical_tank", "Dense Chemical Tank");
        add("block.evolvedmekanism.dense_combining_factory", "Dense Combining Factory");
        add("block.evolvedmekanism.dense_compressing_factory", "Dense Compressing Factory");
        add("block.evolvedmekanism.dense_crushing_factory", "Dense Crushing Factory");
        add("block.evolvedmekanism.dense_energy_cube", "Dense Energy Cube");
        add("block.evolvedmekanism.dense_enriching_factory", "Dense Enriching Factory");
        add("block.evolvedmekanism.dense_fluid_tank", "Dense Fluid Tank");
        add("block.evolvedmekanism.dense_induction_cell", "Dense Induction Cell");
        add("block.evolvedmekanism.dense_induction_provider", "Dense Induction Provider");
        add("block.evolvedmekanism.dense_infusing_factory", "Dense Infusing Factory");
        add("block.evolvedmekanism.dense_injecting_factory", "Dense Injecting Factory");
        add("block.evolvedmekanism.dense_logistical_transporter", "Dense Logistical Transporter");
        add("block.evolvedmekanism.dense_mechanical_pipe", "Dense Mechanical Pipe");
        add("block.evolvedmekanism.dense_pressurized_tube", "Dense Pressurized Tube");
        add("block.evolvedmekanism.dense_purifying_factory", "Dense Purifying Factory");
        add("block.evolvedmekanism.dense_sawing_factory", "Dense Sawing Factory");
        add("block.evolvedmekanism.dense_smelting_factory", "Dense Smelting Factory");
        add("block.evolvedmekanism.dense_alloying_factory", "Dense Alloying Factory");
        add("block.evolvedmekanism.dense_chemixing_factory", "Dense Chemixing Factory");
        add("block.evolvedmekanism.dense_thermodynamic_conductor", "Dense Thermodynamic Conductor");
        add("block.evolvedmekanism.dense_universal_cable", "Dense Universal Cable");
        add("block.evolvedmekanism.dense_personal_barrel", "Dense Personal Barrel");
        add("block.evolvedmekanism.dense_personal_chest", "Dense Personal Chest");
        add("block.evolvedmekanism.multiversal_bin", "Multiversal Bin");
        add("block.evolvedmekanism.multiversal_chemical_tank", "Multiversal Chemical Tank");
        add("block.evolvedmekanism.multiversal_combining_factory", "Multiversal Combining Factory");
        add("block.evolvedmekanism.multiversal_compressing_factory", "Multiversal Compressing Factory");
        add("block.evolvedmekanism.multiversal_crushing_factory", "Multiversal Crushing Factory");
        add("block.evolvedmekanism.multiversal_energy_cube", "Multiversal Energy Cube");
        add("block.evolvedmekanism.multiversal_enriching_factory", "Multiversal Enriching Factory");
        add("block.evolvedmekanism.multiversal_fluid_tank", "Multiversal Fluid Tank");
        add("block.evolvedmekanism.multiversal_induction_cell", "Multiversal Induction Cell");
        add("block.evolvedmekanism.multiversal_induction_provider", "Multiversal Induction Provider");
        add("block.evolvedmekanism.multiversal_infusing_factory", "Multiversal Infusing Factory");
        add("block.evolvedmekanism.multiversal_injecting_factory", "Multiversal Injecting Factory");
        add("block.evolvedmekanism.multiversal_logistical_transporter", "Multiversal Logistical Transporter");
        add("block.evolvedmekanism.multiversal_mechanical_pipe", "Multiversal Mechanical Pipe");
        add("block.evolvedmekanism.multiversal_pressurized_tube", "Multiversal Pressurized Tube");
        add("block.evolvedmekanism.multiversal_purifying_factory", "Multiversal Purifying Factory");
        add("block.evolvedmekanism.multiversal_sawing_factory", "Multiversal Sawing Factory");
        add("block.evolvedmekanism.multiversal_smelting_factory", "Multiversal Smelting Factory");
        add("block.evolvedmekanism.multiversal_alloying_factory", "Multiversal Alloying Factory");
        add("block.evolvedmekanism.multiversal_chemixing_factory", "Multiversal Chemixing Factory");
        add("block.evolvedmekanism.multiversal_thermodynamic_conductor", "Multiversal Thermodynamic Conductor");
        add("block.evolvedmekanism.multiversal_universal_cable", "Multiversal Universal Cable");
        add("block.evolvedmekanism.multiversal_personal_barrel", "Multiversal Personal Barrel");
        add("block.evolvedmekanism.multiversal_personal_chest", "Multiversal Personal Chest");
        add("block.evolvedmekanism.creative_combining_factory", "Creative Combining Factory");
        add("block.evolvedmekanism.creative_compressing_factory", "Creative Compressing Factory");
        add("block.evolvedmekanism.creative_crushing_factory", "Creative Crushing Factory");
        add("block.evolvedmekanism.creative_enriching_factory", "Creative Enriching Factory");
        add("block.evolvedmekanism.creative_induction_cell", "Creative Induction Cell");
        add("block.evolvedmekanism.creative_induction_provider", "Creative Induction Provider");
        add("block.evolvedmekanism.creative_infusing_factory", "Creative Infusing Factory");
        add("block.evolvedmekanism.creative_injecting_factory", "Creative Injecting Factory");
        add("block.evolvedmekanism.creative_logistical_transporter", "Creative Logistical Transporter");
        add("block.evolvedmekanism.creative_mechanical_pipe", "Creative Mechanical Pipe");
        add("block.evolvedmekanism.creative_pressurized_tube", "Creative Pressurized Tube");
        add("block.evolvedmekanism.creative_purifying_factory", "Creative Purifying Factory");
        add("block.evolvedmekanism.creative_sawing_factory", "Creative Sawing Factory");
        add("block.evolvedmekanism.creative_smelting_factory", "Creative Smelting Factory");
        add("block.evolvedmekanism.creative_alloying_factory", "Creative Alloying Factory");
        add("block.evolvedmekanism.creative_chemixing_factory", "Creative Chemixing Factory");
        add("block.evolvedmekanism.creative_thermodynamic_conductor", "Creative Thermodynamic Conductor");
        add("block.evolvedmekanism.creative_universal_cable", "Creative Universal Cable");
        add("block.evolvedmekanism.creative_personal_barrel", "Creative Personal Barrel");
        add("block.evolvedmekanism.creative_personal_chest", "Creative Personal Chest");
        add("block.evolvedmekanism.block_better_gold", "Better Gold Block");
        add("block.evolvedmekanism.block_plaslitherite", "Plaslitherite Block");
        add("block.evolvedmekanism.block_noctis_rozuli", "Noctis Rozuli Block");
        add("block.evolvedmekanism.block_alloy_infused", "Infused Alloy Block");
        add("block.evolvedmekanism.block_alloy_reinforced", "Reinforced Alloy Block");
        add("block.evolvedmekanism.block_alloy_atomic", "Atomic Alloy Block");
        add("block.evolvedmekanism.block_alloy_hypercharged", "Hypercharged Alloy Block");
        add("block.evolvedmekanism.block_alloy_subatomic", "Subatomic Alloy Block");
        add("block.evolvedmekanism.block_alloy_singular", "Singular Alloy Block");
        add("block.evolvedmekanism.block_alloy_exoversal", "Exoversal Alloy Block");
        add("block.evolvedmekanism.block_alloy_creative", "Creative Alloy Block");
        add("block.evolvedmekanism.apt_casing", "APT Casing");
        add("block.evolvedmekanism.apt_port", "APT Port");
        add("block.evolvedmekanism.advanced_solar_generator", "Advanced Solar Generator");
        add("block.evolvedmekanism.elite_solar_generator", "Elite Solar Generator");
        add("block.evolvedmekanism.ultimate_solar_generator", "Ultimate Solar Generator");
        add("block.evolvedmekanism.overclocked_solar_generator", "Overclocked Solar Generator");
        add("block.evolvedmekanism.quantum_solar_generator", "Quantum Solar Generator");
        add("block.evolvedmekanism.dense_solar_generator", "Dense Solar Generator");
        add("block.evolvedmekanism.multiversal_solar_generator", "Multiversal Solar Generator");
        add("block.evolvedmekanism.creative_solar_generator", "Creative Solar Generator");
        add("block.evolvedmekanism.lunar_generator", "Lunar Generator");
        add("block.evolvedmekanism.basic_advanced_lunar_generator", "Basic Advanced Lunar Generator");
        add("block.evolvedmekanism.lunar_neutron_activator", "Lunar Neutron Activator");
        add("block.evolvedmekanism.advanced_lunar_generator", "Advanced Lunar Generator");
        add("block.evolvedmekanism.advanced_lunar_generator2", "Advanced Lunar Generator");
        add("block.evolvedmekanism.elite_lunar_generator", "Elite Lunar Generator");
        add("block.evolvedmekanism.ultimate_lunar_generator", "Ultimate Lunar Generator");
        add("block.evolvedmekanism.overclocked_lunar_generator", "Overclocked Lunar Generator");
        add("block.evolvedmekanism.quantum_lunar_generator", "Quantum Lunar Generator");
        add("block.evolvedmekanism.dense_lunar_generator", "Dense Lunar Generator");
        add("block.evolvedmekanism.multiversal_lunar_generator", "Multiversal Lunar Generator");
        add("block.evolvedmekanism.creative_lunar_generator", "Creative Lunar Generator");
        add("block.evolvedmekanism.depthrock_fluorite_ore", "Depthrock Fluorite Ore");
        add("block.evolvedmekanism.depthrock_lead_ore", "Depthrock Lead Ore");
        add("block.evolvedmekanism.depthrock_osmium_ore", "Depthrock Osmium Ore");
        add("block.evolvedmekanism.depthrock_tin_ore", "Depthrock Tin Ore");
        add("block.evolvedmekanism.depthrock_uranium_ore", "Depthrock Uranium Ore");
        add("block.evolvedmekanism.end_stone_fluorite_ore", "End Stone Fluorite Ore");
        add("block.evolvedmekanism.end_stone_lead_ore", "End Stone Lead Ore");
        add("block.evolvedmekanism.end_stone_osmium_ore", "End Stone Osmium Ore");
        add("block.evolvedmekanism.end_stone_tin_ore", "End Stone Tin Ore");
        add("block.evolvedmekanism.end_stone_uranium_ore", "End Stone Uranium Ore");
        add("block.evolvedmekanism.holystone_fluorite_ore", "Holystone Fluorite Ore");
        add("block.evolvedmekanism.holystone_lead_ore", "Holystone Lead Ore");
        add("block.evolvedmekanism.holystone_osmium_ore", "Holystone Osmium Ore");
        add("block.evolvedmekanism.holystone_tin_ore", "Holystone Tin Ore");
        add("block.evolvedmekanism.holystone_uranium_ore", "Holystone Uranium Ore");
        add("block.evolvedmekanism.netherrack_fluorite_ore", "Netherrack Fluorite Ore");
        add("block.evolvedmekanism.netherrack_lead_ore", "Netherrack Lead Ore");
        add("block.evolvedmekanism.netherrack_osmium_ore", "Netherrack Osmium Ore");
        add("block.evolvedmekanism.netherrack_tin_ore", "Netherrack Tin Ore");
        add("block.evolvedmekanism.netherrack_uranium_ore", "Netherrack Uranium Ore");
        add("block.evolvedmekanism.shiverstone_fluorite_ore", "Shiverstone Fluorite Ore");
        add("block.evolvedmekanism.shiverstone_lead_ore", "Shiverstone Lead Ore");
        add("block.evolvedmekanism.shiverstone_osmium_ore", "Shiverstone Osmium Ore");
        add("block.evolvedmekanism.shiverstone_tin_ore", "Shiverstone Tin Ore");
        add("block.evolvedmekanism.shiverstone_uranium_ore", "Shiverstone Uranium Ore");
        add("block.evolvedmekanism.noctis_ore", "Noctis Rozuli Ore");
        add("block.evolvedmekanism.deepslate_noctis_ore", "Deepslate Noctis Rozuli Ore");
        add("block.evolvedmekanism.noctis_rozuli_ore", "Noctis Rozuli Ore");
        add("block.evolvedmekanism.deepslate_noctis_rozuli_ore", "Deepslate Noctis Rozuli Ore");
        add("block.evolvedmekanism.supercharging_element", "Supercharging Element");
        add("block.evolvedmekanism.block_refined_redstone", "Refined Redstone");
        add("container.evolvedmekanism.alloyer", "Alloyer");
        add("container.evolvedmekanism.chemixer", "Chemixer");
        add("container.evolvedmekanism.thermalizer", "Thermalizer");
        add("container.evolvedmekanism.solidification_chamber", "Solidification Chamber");
        add("container.mekanism.basic_alloying_factory", "Basic Alloying Factory");
        add("container.mekanism.basic_chemixing_factory", "Basic Chemixing Factory");
        add("container.mekanism.advanced_alloying_factory", "Advanced Alloying Factory");
        add("container.mekanism.advanced_chemixing_factory", "Advanced Chemixing Factory");
        add("container.evolvedmekanism.advanced_personal_barrel", "Advanced Personal Barrel");
        add("container.evolvedmekanism.advanced_personal_chest", "Advanced Personal Chest");
        add("container.mekanism.elite_alloying_factory", "Elite Alloying Factory");
        add("container.mekanism.elite_chemixing_factory", "Elite Chemixing Factory");
        add("container.evolvedmekanism.elite_personal_barrel", "Elite Personal Barrel");
        add("container.evolvedmekanism.elite_personal_chest", "Elite Personal Chest");
        add("container.mekanism.ultimate_alloying_factory", "Ultimate Alloying Factory");
        add("container.mekanism.ultimate_chemixing_factory", "Ultimate Chemixing Factory");
        add("container.evolvedmekanism.ultimate_personal_barrel", "Ultimate Personal Barrel");
        add("container.evolvedmekanism.ultimate_personal_chest", "Ultimate Personal Chest");
        add("container.evolvedmekanism.overclocked_chemical_tank", "Overclocked Chemical Tank");
        add("container.evolvedmekanism.overclocked_combining_factory", "Overclocked Combining Factory");
        add("container.evolvedmekanism.overclocked_compressing_factory", "Overclocked Compressing Factory");
        add("container.evolvedmekanism.overclocked_crushing_factory", "Overclocked Crushing Factory");
        add("container.evolvedmekanism.overclocked_energy_cube", "Overclocked Energy Cube");
        add("container.evolvedmekanism.overclocked_enriching_factory", "Overclocked Enriching Factory");
        add("container.evolvedmekanism.overclocked_fluid_tank", "Overclocked Fluid Tank");
        add("container.evolvedmekanism.overclocked_infusing_factory", "Overclocked Infusing Factory");
        add("container.evolvedmekanism.overclocked_injecting_factory", "Overclocked Injecting Factory");
        add("container.evolvedmekanism.overclocked_purifying_factory", "Overclocked Purifying Factory");
        add("container.evolvedmekanism.overclocked_sawing_factory", "Overclocked Sawing Factory");
        add("container.evolvedmekanism.overclocked_smelting_factory", "Overclocked Smelting Factory");
        add("container.evolvedmekanism.overclocked_alloying_factory", "Overclocked Alloying Factory");
        add("container.evolvedmekanism.overclocked_chemixing_factory", "Overclocked Chemixing Factory");
        add("container.evolvedmekanism.overclocked_personal_barrel", "Overclocked Personal Barrel");
        add("container.evolvedmekanism.overclocked_personal_chest", "Overclocked Personal Chest");
        add("container.evolvedmekanism.quantum_chemical_tank", "Quantum Chemical Tank");
        add("container.evolvedmekanism.quantum_combining_factory", "Quantum Combining Factory");
        add("container.evolvedmekanism.quantum_compressing_factory", "Quantum Compressing Factory");
        add("container.evolvedmekanism.quantum_crushing_factory", "Quantum Crushing Factory");
        add("container.evolvedmekanism.quantum_energy_cube", "Quantum Energy Cube");
        add("container.evolvedmekanism.quantum_enriching_factory", "Quantum Enriching Factory");
        add("container.evolvedmekanism.quantum_fluid_tank", "Quantum Fluid Tank");
        add("container.evolvedmekanism.quantum_infusing_factory", "Quantum Infusing Factory");
        add("container.evolvedmekanism.quantum_injecting_factory", "Quantum Injecting Factory");
        add("container.evolvedmekanism.quantum_purifying_factory", "Quantum Purifying Factory");
        add("container.evolvedmekanism.quantum_sawing_factory", "Quantum Sawing Factory");
        add("container.evolvedmekanism.quantum_smelting_factory", "Quantum Smelting Factory");
        add("container.evolvedmekanism.quantum_alloying_factory", "Quantum Alloying Factory");
        add("container.evolvedmekanism.quantum_chemixing_factory", "Quantum Chemixing Factory");
        add("container.evolvedmekanism.quantum_personal_barrel", "Quantum Personal Barrel");
        add("container.evolvedmekanism.quantum_personal_chest", "Quantum Personal Chest");
        add("container.evolvedmekanism.dense_chemical_tank", "Dense Chemical Tank");
        add("container.evolvedmekanism.dense_combining_factory", "Dense Combining Factory");
        add("container.evolvedmekanism.dense_compressing_factory", "Dense Compressing Factory");
        add("container.evolvedmekanism.dense_crushing_factory", "Dense Crushing Factory");
        add("container.evolvedmekanism.dense_energy_cube", "Dense Energy Cube");
        add("container.evolvedmekanism.dense_enriching_factory", "Dense Enriching Factory");
        add("container.evolvedmekanism.dense_fluid_tank", "Dense Fluid Tank");
        add("container.evolvedmekanism.dense_infusing_factory", "Dense Infusing Factory");
        add("container.evolvedmekanism.dense_injecting_factory", "Dense Injecting Factory");
        add("container.evolvedmekanism.dense_purifying_factory", "Dense Purifying Factory");
        add("container.evolvedmekanism.dense_sawing_factory", "Dense Sawing Factory");
        add("container.evolvedmekanism.dense_smelting_factory", "Dense Smelting Factory");
        add("container.evolvedmekanism.dense_alloying_factory", "Dense Alloying Factory");
        add("container.evolvedmekanism.dense_chemixing_factory", "Dense Chemixing Factory");
        add("container.evolvedmekanism.dense_personal_barrel", "Dense Personal Barrel");
        add("container.evolvedmekanism.dense_personal_chest", "Dense Personal Chest");
        add("container.evolvedmekanism.multiversal_chemical_tank", "Multiversal Chemical Tank");
        add("container.evolvedmekanism.multiversal_combining_factory", "Multiversal Combining Factory");
        add("container.evolvedmekanism.multiversal_compressing_factory", "Multiversal Compressing Factory");
        add("container.evolvedmekanism.multiversal_crushing_factory", "Multiversal Crushing Factory");
        add("container.evolvedmekanism.multiversal_energy_cube", "Multiversal Energy Cube");
        add("container.evolvedmekanism.multiversal_enriching_factory", "Multiversal Enriching Factory");
        add("container.evolvedmekanism.multiversal_fluid_tank", "Multiversal Fluid Tank");
        add("container.evolvedmekanism.multiversal_infusing_factory", "Multiversal Infusing Factory");
        add("container.evolvedmekanism.multiversal_injecting_factory", "Multiversal Injecting Factory");
        add("container.evolvedmekanism.multiversal_purifying_factory", "Multiversal Purifying Factory");
        add("container.evolvedmekanism.multiversal_sawing_factory", "Multiversal Sawing Factory");
        add("container.evolvedmekanism.multiversal_smelting_factory", "Multiversal Smelting Factory");
        add("container.evolvedmekanism.multiversal_alloying_factory", "Multiversal Alloying Factory");
        add("container.evolvedmekanism.multiversal_chemixing_factory", "Multiversal Chemixing Factory");
        add("container.evolvedmekanism.multiversal_personal_barrel", "Multiversal Personal Barrel");
        add("container.evolvedmekanism.multiversal_personal_chest", "Multiversal Personal Chest");
        add("container.evolvedmekanism.creative_combining_factory", "Creative Combining Factory");
        add("container.evolvedmekanism.creative_compressing_factory", "Creative Compressing Factory");
        add("container.evolvedmekanism.creative_crushing_factory", "Creative Crushing Factory");
        add("container.evolvedmekanism.creative_enriching_factory", "Creative Enriching Factory");
        add("container.evolvedmekanism.creative_infusing_factory", "Creative Infusing Factory");
        add("container.evolvedmekanism.creative_injecting_factory", "Creative Injecting Factory");
        add("container.evolvedmekanism.creative_purifying_factory", "Creative Purifying Factory");
        add("container.evolvedmekanism.creative_sawing_factory", "Creative Sawing Factory");
        add("container.evolvedmekanism.creative_smelting_factory", "Creative Smelting Factory");
        add("container.evolvedmekanism.creative_alloying_factory", "Creative Alloying Factory");
        add("container.evolvedmekanism.creative_chemixing_factory", "Creative Chemixing Factory");
        add("container.evolvedmekanism.creative_personal_barrel", "Creative Personal Barrel");
        add("container.evolvedmekanism.creative_personal_chest", "Creative Personal Chest");
        add("container.evolvedmekanism.advanced_solar_generator", "Advanced Solar Generator");
        add("container.evolvedmekanism.elite_solar_generator", "Elite Solar Generator");
        add("container.evolvedmekanism.ultimate_solar_generator", "Ultimate Solar Generator");
        add("container.evolvedmekanism.overclocked_solar_generator", "Overclocked Solar Generator");
        add("container.evolvedmekanism.quantum_solar_generator", "Quantum Solar Generator");
        add("container.evolvedmekanism.dense_solar_generator", "Dense Solar Generator");
        add("container.evolvedmekanism.multiversal_solar_generator", "Multiversal Solar Generator");
        add("container.evolvedmekanism.creative_solar_generator", "Creative Solar Generator");
        add("container.evolvedmekanism.lunar_generator", "Lunar Generator");
        add("container.evolvedmekanism.basic_advanced_lunar_generator", "Basic Advanced Lunar Generator");
        add("container.evolvedmekanism.lunar_neutron_activator", "Lunar Neutron Activator");
        add("container.evolvedmekanism.advanced_lunar_generator", "Advanced Lunar Generator");
        add("container.evolvedmekanism.advanced_lunar_generator2", "Advanced Lunar Generator");
        add("container.evolvedmekanism.elite_lunar_generator", "Elite Lunar Generator");
        add("container.evolvedmekanism.ultimate_lunar_generator", "Ultimate Lunar Generator");
        add("container.evolvedmekanism.overclocked_lunar_generator", "Overclocked Lunar Generator");
        add("container.evolvedmekanism.quantum_lunar_generator", "Quantum Lunar Generator");
        add("container.evolvedmekanism.dense_lunar_generator", "Dense Lunar Generator");
        add("container.evolvedmekanism.multiversal_lunar_generator", "Multiversal Lunar Generator");
        add("container.evolvedmekanism.creative_lunar_generator", "Creative Lunar Generator");
        add("item.evolvedmekanism.alloy_hypercharged", "Hypercharged Alloy");
        add("item.evolvedmekanism.alloy_subatomic", "Subatomic Alloy");
        add("item.evolvedmekanism.alloy_singular", "Singular Alloy");
        add("item.evolvedmekanism.alloy_exoversal", "Exoversal Alloy");
        add("item.evolvedmekanism.overclocked_control_circuit", "Overclocked Control Circuit");
        add("item.evolvedmekanism.quantum_control_circuit", "Quantum Control Circuit");
        add("item.evolvedmekanism.dense_control_circuit", "Dense Control Circuit");
        add("item.evolvedmekanism.multiversal_control_circuit", "Multiversal Control Circuit");
        add("item.evolvedmekanism.overclocked_tier_installer", "Overclocked Tier Installer");
        add("item.evolvedmekanism.quantum_tier_installer", "Quantum Tier Installer");
        add("item.evolvedmekanism.dense_tier_installer", "Dense Tier Installer");
        add("item.evolvedmekanism.multiversal_tier_installer", "Multiversal Tier Installer");
        add("item.evolvedmekanism.max_tier_installer", "Maximum Tier Installer");
        add("item.evolvedmekanism.enriched_uranium", "Enriched Uranium");
        add("item.evolvedmekanism.enriched_better_gold", "Enriched Better Gold");
        add("item.evolvedmekanism.enriched_plaslitherite", "Enriched Plaslitherite");
        add("item.evolvedmekanism.ingot_better_gold", "Better Gold Ingot");
        add("item.evolvedmekanism.ingot_plaslitherite", "Plaslitherite Ingot");
        add("item.evolvedmekanism.noctis_rozuli", "Noctis Rozuli");
        add("item.evolvedmekanism.nugget_better_gold", "Better Gold Nugget");
        add("item.evolvedmekanism.nugget_plaslitherite", "Plaslitherite Nugget");
        add("item.evolvedmekanism.dust_better_gold", "Better Gold Dust");
        add("item.evolvedmekanism.dust_plaslitherite", "Plaslitherite Dust");
        add("item.evolvedmekanism.dust_noctis_rozuli", "Noctis Rozuli Dust");
        add("item.evolvedmekanism.qio_drive_boosted", "Boosted QIO Drive");
        add("item.evolvedmekanism.qio_drive_singularity", "Singularity QIO Drive");
        add("item.evolvedmekanism.qio_drive_hypra_solidified", "Hypra-Solidified QIO Drive");
        add("item.evolvedmekanism.qio_drive_black_hole", "Black-Hole QIO Drive");
        add("item.evolvedmekanism.advanced_solar_panel", "Advanced Solar Panel");
        add("item.evolvedmekanism.elite_solar_panel", "Elite Solar Panel");
        add("item.evolvedmekanism.ultimate_solar_panel", "Ultimate Solar Panel");
        add("item.evolvedmekanism.overclocked_solar_panel", "Overclocked Solar Panel");
        add("item.evolvedmekanism.quantum_solar_panel", "Quantum Solar Panel");
        add("item.evolvedmekanism.dense_solar_panel", "Dense Solar Panel");
        add("item.evolvedmekanism.multiversal_solar_panel", "Multiversal Solar Panel");
        add("item.evolvedmekanism.creative_solar_panel", "Creative Solar Panel");
        add("item.evolvedmekanism.advanced_lunar_panel", "Advanced Lunar Panel");
        add("item.evolvedmekanism.elite_lunar_panel", "Elite Lunar Panel");
        add("item.evolvedmekanism.ultimate_lunar_panel", "Ultimate Lunar Panel");
        add("item.evolvedmekanism.overclocked_lunar_panel", "Overclocked Lunar Panel");
        add("item.evolvedmekanism.quantum_lunar_panel", "Quantum Lunar Panel");
        add("item.evolvedmekanism.dense_lunar_panel", "Dense Lunar Panel");
        add("item.evolvedmekanism.multiversal_lunar_panel", "Multiversal Lunar Panel");
        add("item.evolvedmekanism.creative_lunar_panel", "Creative Lunar Panel");
        add("item.evolvedmekanism.lunar_panel", "Lunar Panel");
        add("item.evolvedmekanism.upgrade_radioactive", "Radioactive Upgrade");
        add("item.evolvedmekanism.upgrade_solar", "Solar Upgrade");
        add("item.evolvedmekanism.upgrade_lunar", "Lunar Upgrade");
        add("item.evolvedmekanism.mold_coin", "Coin Mold");
        add("item.evolvedmekanism.mold_dust", "Dust Mold");
        add("item.evolvedmekanism.mold_gear", "Gear Mold");
        add("item.evolvedmekanism.mold_gem", "Gem Mold");
        add("item.evolvedmekanism.mold_ingot", "Ingot Mold");
        add("item.evolvedmekanism.mold_nugget", "Nugget Mold");
        add("item.evolvedmekanism.mold_plate", "Plate Mold");
        add("item.evolvedmekanism.mold_rod", "Rod Mold");
        add("item.evolvedmekanism.mold_storage_block", "Block Mold");
        add("item.evolvedmekanism.mold_wire", "Wire Mold");
        add("item.evolvedmekanism.ingot_refined_redstone", "Refined Redstone Ingot");
        add("item.evolvedmekanism.nugget_refined_redstone", "Refined Redstone Nugget");
        add("infuse_type.evolvedmekanism.uranium", "Uranium");
        add("infuse_type.evolvedmekanism.better_gold", "Better Gold");
        add("infuse_type.evolvedmekanism.plaslitherite", "Plaslitherite");
        add("gas.evolvedmekanism.nitrogen", "Nitrogen");
        add("gas.evolvedmekanism.cryonoctis", "Cryonoctis");
        add("block.evolvedmekanism.nitrogen", "Nitrogen");
        add("block.evolvedmekanism.cryonoctis", "Cryonoctis");
        add("item.evolvedmekanism.nitrogen_bucket", "Nitrogen Bucket");
        add("item.evolvedmekanism.cryonoctis_bucket", "Cryonoctis Bucket");
        add("fluid_type.evolvedmekanism.nitrogen", "Nitrogen");
        add("fluid_type.evolvedmekanism.cryonoctis", "Cryonoctis");
        add("apt.evolvedmekanism.port_mode", "Toggled APT Port mode to: %1$s.");
        add("apt.evolvedmekanism.apt", "Antimatter Protomolecular Transmutator");
        add("tiered_storage.evolvedmekanism.capacity", "Capacity: %s");
        add("item.evolvedmekanism.alloy_creative", "Creative Alloy");
        add("item.evolvedmekanism.creative_control_circuit", "Creative Control Circuit");
        add("item.evolvedmekanism.qio_drive_creative", "Creative QIO Drive");
        add("item.evolvedmekanism.creative_tier_installer", "Creative Tier Installer");
        add("factory.mekanism.alloying", "Alloying");
        add("description.mekanism.alloyer", "A machine used to alloy items together.");
        add("factory.mekanism.chemixing", "Chemixing");
        add("description.mekanism.chemixer", "A machine used to alloy items and gases together.");
        add("description.mekanism.thermalizer", "A machine used to melt items into their fluid version.");
        add("description.mekanism.solidification_chamber", "A machine used to solidify fluids into their item version.");
        add("description.evolvedmekanism.apt_casing", "Reinforced antimattered casing capable of resisting intense chemical and thermal effects from transmutating reactions.");
        add("description.evolvedmekanism.apt_port", "A port used for the transfer of energy and substances in the Antimatter Protomolecular Transmutator.");
        add("module.evolvedmekanism.air_affinity_unit", "Air Affinity Unit");
        add("description.evolvedmekanism.air_affinity_unit", "Disables the mining malus effect when flying.");
        add("module.evolvedmekanism.aoe_unit", "AOE Unit");
        add("description.evolvedmekanism.aoe_unit", "Increases the area of effect of tools.");
        add("module.evolvedmekanism.aqua_affinity_unit", "Aqua Affinity Unit");
        add("description.evolvedmekanism.aqua_affinity_unit", "Disables the mining malus effect when underwater.");
        add("module.evolvedmekanism.bee_shielding_unit", "Bee Shielding Unit");
        add("description.evolvedmekanism.bee_shielding_unit", "Provides thick, bee-proof metal plating to any MekaSuit armor piece.");
        add("module.evolvedmekanism.capturing_unit", "Capturing Unit");
        add("description.evolvedmekanism.capturing_unit", "Provides a chance to loot mobs spawn eggs when killing them.");
        add("module.evolvedmekanism.luck_unit", "Luck Unit");
        add("description.evolvedmekanism.luck_unit", "Increases the chance of getting better loots.");
        add("module.evolvedmekanism.thermal_shielding_unit", "Thermal Shielding Unit");
        add("description.evolvedmekanism.thermal_shielding_unit", "Provides thick, thermal-proof metal plating to any MekaSuit armor piece.");
        add("description.evolvedmekanism.advanced_solar_generator", "An advanced generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.elite_solar_generator", "An elite generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.ultimate_solar_generator", "An ultimate generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.overclocked_solar_generator", "An overclocked generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.quantum_solar_generator", "A quantum generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.dense_solar_generator", "A dense generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.multiversal_solar_generator", "A multiversal generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.creative_solar_generator", "A creative generator that directly absorbs the sun's rays with little loss to produce energy.");
        add("description.evolvedmekanism.lunar_generator", "A generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.basic_advanced_lunar_generator", "A compact advanced generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.lunar_neutron_activator", "A machine that uses moonlight to activate gases, converting them into other gases.");
        add("description.mekanism.lunar_neutron_activator", "A machine that uses moonlight to activate gases, converting them into other gases.");
        add("description.evolvedmekanism.advanced_lunar_generator", "An advanced generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.advanced_lunar_generator2", "An advanced generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.elite_lunar_generator", "An elite generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.ultimate_lunar_generator", "An ultimate generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.overclocked_lunar_generator", "An overclocked generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.quantum_lunar_generator", "A quantum generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.dense_lunar_generator", "A dense generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.multiversal_lunar_generator", "A multiversal generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.creative_lunar_generator", "A creative generator that directly absorbs the moon's rays with little loss to produce energy.");
        add("description.evolvedmekanism.supercharging_element", "A modular, somewhat dangerous charger that is capable of charging the APT massively.");
        add("description.evolvedmekanism.max_tier_installer", "Directly upgrades compatible machines up to the %s tier.");
        add("description.evolvedmekanism.noctis_rozuli_ore", "Some whisper that it can only be harvested when darkness falls and the moon's light guides the way.");
        add("trim_material.evolvedmekanism.noctis_rozuli", "Noctis Rozuli");
        add("upgrade.mekanism.radioactive", "Radioactive");
        add("upgrade.mekanism.radioactive.description", "Allow radioactive gas insertion.");
        add("upgrade.mekanism.solar", "Solar");
        add("upgrade.mekanism.solar.description", "Increases solar production of generators.");
        add("upgrade.mekanism.lunar", "Lunar");
        add("upgrade.mekanism.lunar.description", "Increases lunar production of generators.");
        add("tooltip.evolvedmekanism.not_consumed", "Not Consumed");
        add("block.evolvedmekanism.molten_copper", "Molten Copper");
        add("block.evolvedmekanism.molten_amethyst", "Molten Amethyst");
        add("block.evolvedmekanism.molten_coal", "Molten Coal");
        add("block.evolvedmekanism.molten_diamond", "Molten Diamond");
        add("block.evolvedmekanism.molten_emerald", "Molten Emerald");
        add("block.evolvedmekanism.molten_ender", "Molten Ender");
        add("block.evolvedmekanism.molten_blaze", "Molten Blaze");
        add("block.evolvedmekanism.molten_clay", "Molten Clay");
        add("block.evolvedmekanism.molten_glass", "Molten Glass");
        add("block.evolvedmekanism.molten_redstone", "Molten Redstone");
        add("block.evolvedmekanism.molten_obsidian", "Molten Obsidian");
        add("block.evolvedmekanism.molten_quartz", "Molten Quartz");
        add("block.evolvedmekanism.molten_slime", "Molten Slime");
        add("block.evolvedmekanism.molten_soul", "Molten Soul");
        add("block.evolvedmekanism.molten_aluminum", "Molten Aluminum");
        add("block.evolvedmekanism.molten_brass", "Molten Brass");
        add("block.evolvedmekanism.molten_bronze", "Molten Bronze");
        add("block.evolvedmekanism.molten_cobalt", "Molten Cobalt");
        add("block.evolvedmekanism.molten_constantan", "Molten Constantan");
        add("block.evolvedmekanism.molten_electrum", "Molten Electrum");
        add("block.evolvedmekanism.molten_enderium", "Molten Enderium");
        add("block.evolvedmekanism.molten_gold", "Molten Gold");
        add("block.evolvedmekanism.molten_hepatizon", "Molten Hepatizon");
        add("block.evolvedmekanism.molten_invar", "Molten Invar");
        add("block.evolvedmekanism.molten_iron", "Molten Iron");
        add("block.evolvedmekanism.molten_knightslime", "Molten Knightslime");
        add("block.evolvedmekanism.molten_lead", "Molten Lead");
        add("block.evolvedmekanism.molten_lumium", "Molten Lumium");
        add("block.evolvedmekanism.molten_manyullyn", "Molten Manyullyn");
        add("block.evolvedmekanism.molten_netherite", "Molten Netherite");
        add("block.evolvedmekanism.molten_nickel", "Molten Nickel");
        add("block.evolvedmekanism.molten_osmium", "Molten Osmium");
        add("block.evolvedmekanism.molten_pewter", "Molten Pewter");
        add("block.evolvedmekanism.molten_pig_iron", "Molten Pig Iron");
        add("block.evolvedmekanism.molten_platinum", "Molten Platinum");
        add("block.evolvedmekanism.molten_queens_slime", "Molten Queens Slime");
        add("block.evolvedmekanism.molten_refined_glowstone", "Molten Refined Glowstone");
        add("block.evolvedmekanism.molten_refined_obsidian", "Molten Refined Obsidian");
        add("block.evolvedmekanism.molten_refined_redstone", "Molten Refined Redstone");
        add("block.evolvedmekanism.molten_rose_gold", "Molten Rose Gold");
        add("block.evolvedmekanism.molten_signalum", "Molten Signalum");
        add("block.evolvedmekanism.molten_silicon_bronze", "Molten Silicon Bronze");
        add("block.evolvedmekanism.molten_silver", "Molten Silver");
        add("block.evolvedmekanism.molten_slimesteel", "Molten Slimesteel");
        add("block.evolvedmekanism.molten_soulsteel", "Molten Soulsteel");
        add("block.evolvedmekanism.molten_steel", "Molten Steel");
        add("block.evolvedmekanism.molten_tin", "Molten Tin");
        add("block.evolvedmekanism.molten_tungsten", "Molten Tungsten");
        add("block.evolvedmekanism.molten_uranium", "Molten Uranium");
        add("block.evolvedmekanism.molten_zinc", "Molten Zinc");
        add("block.evolvedmekanism.molten_veridium", "Molten Veridium");
        add("block.evolvedmekanism.molten_gravitite", "Molten Gravitite");
        add("block.evolvedmekanism.molten_stratus", "Molten Stratus");
        add("block.evolvedmekanism.molten_desh", "Molten Desh");
        add("block.evolvedmekanism.molten_ostrum", "Molten Ostrum");
        add("block.evolvedmekanism.molten_calorite", "Molten Calorite");
        add("block.evolvedmekanism.molten_juperium", "Molten Juperium");
        add("block.evolvedmekanism.molten_saturlyte", "Molten Saturlyte");
        add("block.evolvedmekanism.molten_neptunium", "Molten Neptunium");
        add("block.evolvedmekanism.molten_radium", "Molten Radium");
        add("block.evolvedmekanism.molten_plutonium", "Molten Plutonium");
        add("block.evolvedmekanism.molten_electrolyte", "Molten Electrolyte");
        add("block.evolvedmekanism.molten_blutonium", "Molten Blutonium");
        add("block.evolvedmekanism.molten_cyanite", "Molten Cyanite");
        add("block.evolvedmekanism.molten_graphite", "Molten Graphite");
        add("block.evolvedmekanism.molten_ludicrite", "Molten Ludicrite");
        add("block.evolvedmekanism.molten_hellforged", "Molten Hellforged");
        add("block.evolvedmekanism.molten_manasteel", "Molten Manasteel");
        add("block.evolvedmekanism.molten_terrasteel", "Molten Terrasteel");
        add("block.evolvedmekanism.molten_elementium", "Molten Elementium");
        add("block.evolvedmekanism.molten_alfsteel", "Molten Alfsteel");
        add("block.evolvedmekanism.molten_gaiasteel", "Molten Gaiasteel");
        add("block.evolvedmekanism.molten_copper_alloy", "Molten Copper Alloy");
        add("block.evolvedmekanism.molten_energetic_alloy", "Molten Energetic Alloy");
        add("block.evolvedmekanism.molten_vibrant_alloy", "Molten Vibrant Alloy");
        add("block.evolvedmekanism.molten_redstone_alloy", "Molten Redstone Alloy");
        add("block.evolvedmekanism.molten_conductive_alloy", "Molten Conductive Alloy");
        add("block.evolvedmekanism.molten_pulsating_alloy", "Molten Pulsating Alloy");
        add("block.evolvedmekanism.molten_dark_steel", "Molten Dark Steel");
        add("block.evolvedmekanism.molten_soularium", "Molten Soularium");
        add("block.evolvedmekanism.molten_end_steel", "Molten End Steel");
        add("block.evolvedmekanism.molten_pink_slime", "Molten Pink Slime");
        add("block.evolvedmekanism.molten_better_gold", "Molten Better Gold");
        add("block.evolvedmekanism.molten_plaslitherite", "Molten Plaslitherite");
        add("block.evolvedmekanism.molten_prosperity", "Molten Prosperity");
        add("block.evolvedmekanism.molten_soulium", "Molten Soulium");
        add("block.evolvedmekanism.molten_inferium", "Molten Inferium");
        add("block.evolvedmekanism.molten_prudentium", "Molten Prudentium");
        add("block.evolvedmekanism.molten_tertium", "Molten Tertium");
        add("block.evolvedmekanism.molten_imperium", "Molten Imperium");
        add("block.evolvedmekanism.molten_supremium", "Molten Supremium");
        add("block.evolvedmekanism.molten_awakened_supremium", "Molten Awakened Supremium");
        add("block.evolvedmekanism.molten_insanium", "Molten Insanium");
        add("block.evolvedmekanism.molten_ornium", "Molten Ornium");
        add("block.evolvedmekanism.molten_lightium", "Molten Lightium");
        add("block.evolvedmekanism.molten_tornium", "Molten Tornium");
        add("block.evolvedmekanism.molten_ouranium", "Molten Ouranium");
        add("block.evolvedmekanism.molten_infused_iron", "Molten Infused Iron");
        add("block.evolvedmekanism.molten_tainted_gold", "Molten Tainted Gold");
        add("block.evolvedmekanism.molten_lithium", "Molten Lithium");
        add("block.evolvedmekanism.molten_thorium", "Molten Thorium");
        add("block.evolvedmekanism.molten_magnesium", "Molten Magnesium");
        add("block.evolvedmekanism.molten_neutronium", "Molten Neutronium");
        add("block.evolvedmekanism.molten_titanium", "Molten Titanium");
        add("block.evolvedmekanism.molten_manganese", "Molten Manganese");
        add("block.evolvedmekanism.molten_iridium", "Molten Iridium");
        add("block.evolvedmekanism.molten_boron", "Molten Boron");
        add("block.evolvedmekanism.molten_iesnium", "Molten Iesnium");
        add("block.evolvedmekanism.molten_oratchalcum", "Molten Oratchalcum");
        add("block.evolvedmekanism.molten_prismalium", "Molten Prismalium");
        add("block.evolvedmekanism.molten_melodium", "Molten Melodium");
        add("block.evolvedmekanism.molten_stellarium", "Molten Stellarium");
        add("block.evolvedmekanism.molten_flux", "Molten Flux-Infused");
        add("block.evolvedmekanism.molten_draconium", "Molten Draconium");
        add("block.evolvedmekanism.molten_awakened_draconium", "Molten Awakened Draconium");
        add("block.evolvedmekanism.molten_black_iron", "Molten Black Iron");
        add("block.evolvedmekanism.molten_redstone_ingot", "Molten Redstone Ingot");
        add("block.evolvedmekanism.molten_enhanced_redstone_ingot", "Molten Enhanced Redstone Ingot");
        add("block.evolvedmekanism.molten_ender_ingot", "Molten Ender Ingot");
        add("block.evolvedmekanism.molten_enhanced_ender_ingot", "Molten Enhanced Ender Ingot");
        add("block.evolvedmekanism.molten_crystaltine", "Molten Crystaltine");
        add("block.evolvedmekanism.molten_the_ultimate", "Molten The Ultimate");
        add("block.evolvedmekanism.molten_infinity", "Molten Infinity");
        add("block.evolvedmekanism.molten_chorium", "Molten Chorium");
        add("block.evolvedmekanism.molten_sentrite", "Molten Sentrite");
        add("block.evolvedmekanism.molten_compressed_iron", "Molten Compressed Iron");
        add("block.evolvedmekanism.molten_nether_star", "Molten Nether Star");
        add("block.evolvedmekanism.molten_certus_quartz", "Molten Certus Quartz");
        add("block.evolvedmekanism.molten_fluix", "Molten Fluix");
        add("block.evolvedmekanism.molten_skyjade", "Molten Skyjade");
        add("block.evolvedmekanism.molten_ambrosium", "Molten Ambrosium");
        add("block.evolvedmekanism.molten_zanite", "Molten Zanite");
        add("block.evolvedmekanism.molten_lapis", "Molten Lapis");
        add("block.evolvedmekanism.molten_noctis", "Molten Noctis");
        add("block.evolvedmekanism.molten_glowstone", "Molten Glowstone");
        add("block.evolvedmekanism.molten_debris", "Molten Debris");
        add("item.evolvedmekanism.molten_copper_bucket", "Molten Copper Bucket");
        add("item.evolvedmekanism.molten_amethyst_bucket", "Molten Amethyst Bucket");
        add("item.evolvedmekanism.molten_coal_bucket", "Molten Coal Bucket");
        add("item.evolvedmekanism.molten_diamond_bucket", "Molten Diamond Bucket");
        add("item.evolvedmekanism.molten_emerald_bucket", "Molten Emerald Bucket");
        add("item.evolvedmekanism.molten_ender_bucket", "Molten Ender Bucket");
        add("item.evolvedmekanism.molten_blaze_bucket", "Molten Blaze Bucket");
        add("item.evolvedmekanism.molten_clay_bucket", "Molten Clay Bucket");
        add("item.evolvedmekanism.molten_glass_bucket", "Molten Glass Bucket");
        add("item.evolvedmekanism.molten_redstone_bucket", "Molten Redstone Bucket");
        add("item.evolvedmekanism.molten_obsidian_bucket", "Molten Obsidian Bucket");
        add("item.evolvedmekanism.molten_quartz_bucket", "Molten Quartz Bucket");
        add("item.evolvedmekanism.molten_slime_bucket", "Molten Slime Bucket");
        add("item.evolvedmekanism.molten_soul_bucket", "Molten Soul Bucket");
        add("item.evolvedmekanism.molten_aluminum_bucket", "Molten Aluminum Bucket");
        add("item.evolvedmekanism.molten_brass_bucket", "Molten Brass Bucket");
        add("item.evolvedmekanism.molten_bronze_bucket", "Molten Bronze Bucket");
        add("item.evolvedmekanism.molten_cobalt_bucket", "Molten Cobalt Bucket");
        add("item.evolvedmekanism.molten_constantan_bucket", "Molten Constantan Bucket");
        add("item.evolvedmekanism.molten_electrum_bucket", "Molten Electrum Bucket");
        add("item.evolvedmekanism.molten_enderium_bucket", "Molten Enderium Bucket");
        add("item.evolvedmekanism.molten_gold_bucket", "Molten Gold Bucket");
        add("item.evolvedmekanism.molten_hepatizon_bucket", "Molten Hepatizon Bucket");
        add("item.evolvedmekanism.molten_invar_bucket", "Molten Invar Bucket");
        add("item.evolvedmekanism.molten_iron_bucket", "Molten Iron Bucket");
        add("item.evolvedmekanism.molten_knightslime_bucket", "Molten Knightslime Bucket");
        add("item.evolvedmekanism.molten_lead_bucket", "Molten Lead Bucket");
        add("item.evolvedmekanism.molten_lumium_bucket", "Molten Lumium Bucket");
        add("item.evolvedmekanism.molten_manyullyn_bucket", "Molten Manyullyn Bucket");
        add("item.evolvedmekanism.molten_netherite_bucket", "Molten Netherite Bucket");
        add("item.evolvedmekanism.molten_nickel_bucket", "Molten Nickel Bucket");
        add("item.evolvedmekanism.molten_osmium_bucket", "Molten Osmium Bucket");
        add("item.evolvedmekanism.molten_pewter_bucket", "Molten Pewter Bucket");
        add("item.evolvedmekanism.molten_pig_iron_bucket", "Molten Pig Iron Bucket");
        add("item.evolvedmekanism.molten_platinum_bucket", "Molten Platinum Bucket");
        add("item.evolvedmekanism.molten_queens_slime_bucket", "Molten Queens Slime Bucket");
        add("item.evolvedmekanism.molten_refined_glowstone_bucket", "Molten Refined Glowstone Bucket");
        add("item.evolvedmekanism.molten_refined_obsidian_bucket", "Molten Refined Obsidian Bucket");
        add("item.evolvedmekanism.molten_refined_redstone_bucket", "Molten Refined Redstone Bucket");
        add("item.evolvedmekanism.molten_rose_gold_bucket", "Molten Rose Gold Bucket");
        add("item.evolvedmekanism.molten_signalum_bucket", "Molten Signalum Bucket");
        add("item.evolvedmekanism.molten_silicon_bronze_bucket", "Molten Silicon Bronze Bucket");
        add("item.evolvedmekanism.molten_silver_bucket", "Molten Silver Bucket");
        add("item.evolvedmekanism.molten_slimesteel_bucket", "Molten Slimesteel Bucket");
        add("item.evolvedmekanism.molten_soulsteel_bucket", "Molten Soulsteel Bucket");
        add("item.evolvedmekanism.molten_steel_bucket", "Molten Steel Bucket");
        add("item.evolvedmekanism.molten_tin_bucket", "Molten Tin Bucket");
        add("item.evolvedmekanism.molten_tungsten_bucket", "Molten Tungsten Bucket");
        add("item.evolvedmekanism.molten_uranium_bucket", "Molten Uranium Bucket");
        add("item.evolvedmekanism.molten_zinc_bucket", "Molten Zinc Bucket");
        add("item.evolvedmekanism.molten_veridium_bucket", "Molten Veridium Bucket");
        add("item.evolvedmekanism.molten_gravitite_bucket", "Molten Gravitite Bucket");
        add("item.evolvedmekanism.molten_stratus_bucket", "Molten Stratus Bucket");
        add("item.evolvedmekanism.molten_desh_bucket", "Molten Desh Bucket");
        add("item.evolvedmekanism.molten_ostrum_bucket", "Molten Ostrum Bucket");
        add("item.evolvedmekanism.molten_calorite_bucket", "Molten Calorite Bucket");
        add("item.evolvedmekanism.molten_juperium_bucket", "Molten Juperium Bucket");
        add("item.evolvedmekanism.molten_saturlyte_bucket", "Molten Saturlyte Bucket");
        add("item.evolvedmekanism.molten_neptunium_bucket", "Molten Neptunium Bucket");
        add("item.evolvedmekanism.molten_radium_bucket", "Molten Radium Bucket");
        add("item.evolvedmekanism.molten_plutonium_bucket", "Molten Plutonium Bucket");
        add("item.evolvedmekanism.molten_electrolyte_bucket", "Molten Electrolyte Bucket");
        add("item.evolvedmekanism.molten_blutonium_bucket", "Molten Blutonium Bucket");
        add("item.evolvedmekanism.molten_cyanite_bucket", "Molten Cyanite Bucket");
        add("item.evolvedmekanism.molten_graphite_bucket", "Molten Graphite Bucket");
        add("item.evolvedmekanism.molten_ludicrite_bucket", "Molten Ludicrite Bucket");
        add("item.evolvedmekanism.molten_hellforged_bucket", "Molten Hellforged Bucket");
        add("item.evolvedmekanism.molten_manasteel_bucket", "Molten Manasteel Bucket");
        add("item.evolvedmekanism.molten_terrasteel_bucket", "Molten Terrasteel Bucket");
        add("item.evolvedmekanism.molten_elementium_bucket", "Molten Elementium Bucket");
        add("item.evolvedmekanism.molten_alfsteel_bucket", "Molten Alfsteel Bucket");
        add("item.evolvedmekanism.molten_gaiasteel_bucket", "Molten Gaiasteel Bucket");
        add("item.evolvedmekanism.molten_copper_alloy_bucket", "Molten Copper Alloy Bucket");
        add("item.evolvedmekanism.molten_energetic_alloy_bucket", "Molten Energetic Alloy Bucket");
        add("item.evolvedmekanism.molten_vibrant_alloy_bucket", "Molten Vibrant Alloy Bucket");
        add("item.evolvedmekanism.molten_redstone_alloy_bucket", "Molten Redstone Alloy Bucket");
        add("item.evolvedmekanism.molten_conductive_alloy_bucket", "Molten Conductive Alloy Bucket");
        add("item.evolvedmekanism.molten_pulsating_alloy_bucket", "Molten Pulsating Alloy Bucket");
        add("item.evolvedmekanism.molten_dark_steel_bucket", "Molten Dark Steel Bucket");
        add("item.evolvedmekanism.molten_soularium_bucket", "Molten Soularium Bucket");
        add("item.evolvedmekanism.molten_end_steel_bucket", "Molten End Steel Bucket");
        add("item.evolvedmekanism.molten_pink_slime_bucket", "Molten Pink Slime Bucket");
        add("item.evolvedmekanism.molten_better_gold_bucket", "Molten Better Gold Bucket");
        add("item.evolvedmekanism.molten_plaslitherite_bucket", "Molten Plaslitherite Bucket");
        add("item.evolvedmekanism.molten_prosperity_bucket", "Molten Prosperity Bucket");
        add("item.evolvedmekanism.molten_soulium_bucket", "Molten Soulium Bucket");
        add("item.evolvedmekanism.molten_inferium_bucket", "Molten Inferium Bucket");
        add("item.evolvedmekanism.molten_prudentium_bucket", "Molten Prudentium Bucket");
        add("item.evolvedmekanism.molten_tertium_bucket", "Molten Tertium Bucket");
        add("item.evolvedmekanism.molten_imperium_bucket", "Molten Imperium Bucket");
        add("item.evolvedmekanism.molten_supremium_bucket", "Molten Supremium Bucket");
        add("item.evolvedmekanism.molten_awakened_supremium_bucket", "Molten Awakened Supremium Bucket");
        add("item.evolvedmekanism.molten_insanium_bucket", "Molten Insanium Bucket");
        add("item.evolvedmekanism.molten_ornium_bucket", "Molten Ornium Bucket");
        add("item.evolvedmekanism.molten_lightium_bucket", "Molten Lightium Bucket");
        add("item.evolvedmekanism.molten_tornium_bucket", "Molten Tornium Bucket");
        add("item.evolvedmekanism.molten_ouranium_bucket", "Molten Ouranium Bucket");
        add("item.evolvedmekanism.molten_infused_iron_bucket", "Molten Infused Iron Bucket");
        add("item.evolvedmekanism.molten_tainted_gold_bucket", "Molten Tainted Gold Bucket");
        add("item.evolvedmekanism.molten_lithium_bucket", "Molten Lithium Bucket");
        add("item.evolvedmekanism.molten_thorium_bucket", "Molten Thorium Bucket");
        add("item.evolvedmekanism.molten_magnesium_bucket", "Molten Magnesium Bucket");
        add("item.evolvedmekanism.molten_neutronium_bucket", "Molten Neutronium Bucket");
        add("item.evolvedmekanism.molten_titanium_bucket", "Molten Titanium Bucket");
        add("item.evolvedmekanism.molten_manganese_bucket", "Molten Manganese Bucket");
        add("item.evolvedmekanism.molten_iridium_bucket", "Molten Iridium Bucket");
        add("item.evolvedmekanism.molten_boron_bucket", "Molten Boron Bucket");
        add("item.evolvedmekanism.molten_iesnium_bucket", "Molten Iesnium Bucket");
        add("item.evolvedmekanism.molten_oratchalcum_bucket", "Molten Oratchalcum Bucket");
        add("item.evolvedmekanism.molten_prismalium_bucket", "Molten Prismalium Bucket");
        add("item.evolvedmekanism.molten_melodium_bucket", "Molten Melodium Bucket");
        add("item.evolvedmekanism.molten_stellarium_bucket", "Molten Stellarium Bucket");
        add("item.evolvedmekanism.molten_flux_bucket", "Molten Flux-Infused Bucket");
        add("item.evolvedmekanism.molten_draconium_bucket", "Molten Draconium Bucket");
        add("item.evolvedmekanism.molten_awakened_draconium_bucket", "Molten Awakened Draconium Bucket");
        add("item.evolvedmekanism.molten_black_iron_bucket", "Molten Black Iron Bucket");
        add("item.evolvedmekanism.molten_redstone_ingot_bucket", "Molten Redstone Ingot Bucket");
        add("item.evolvedmekanism.molten_enhanced_redstone_ingot_bucket", "Molten Enhanced Redstone Ingot Bucket");
        add("item.evolvedmekanism.molten_ender_ingot_bucket", "Molten Ender Ingot Bucket");
        add("item.evolvedmekanism.molten_enhanced_ender_ingot_bucket", "Molten Enhanced Ender Ingot Bucket");
        add("item.evolvedmekanism.molten_crystaltine_bucket", "Molten Crystaltine Bucket");
        add("item.evolvedmekanism.molten_the_ultimate_bucket", "Molten The Ultimate Bucket");
        add("item.evolvedmekanism.molten_infinity_bucket", "Molten Infinity Bucket");
        add("item.evolvedmekanism.molten_chorium_bucket", "Molten Chorium Bucket");
        add("item.evolvedmekanism.molten_sentrite_bucket", "Molten Sentrite Bucket");
        add("item.evolvedmekanism.molten_compressed_iron_bucket", "Molten Compressed Iron Bucket");
        add("item.evolvedmekanism.molten_nether_star_bucket", "Molten Nether Star Bucket");
        add("item.evolvedmekanism.molten_certus_quartz_bucket", "Molten Certus Quartz Bucket");
        add("item.evolvedmekanism.molten_fluix_bucket", "Molten Fluix Bucket");
        add("item.evolvedmekanism.molten_skyjade_bucket", "Molten Skyjade Bucket");
        add("item.evolvedmekanism.molten_ambrosium_bucket", "Molten Ambrosium Bucket");
        add("item.evolvedmekanism.molten_zanite_bucket", "Molten Zanite Bucket");
        add("item.evolvedmekanism.molten_lapis_bucket", "Molten Lapis Bucket");
        add("item.evolvedmekanism.molten_noctis_bucket", "Molten Noctis Bucket");
        add("item.evolvedmekanism.molten_glowstone_bucket", "Molten Glowstone Bucket");
        add("item.evolvedmekanism.molten_debris_bucket", "Molten Debris Bucket");
        add("item.evolvedmekanism.better_gold_axe", "Better Gold Axe");
        add("item.evolvedmekanism.better_gold_boots", "Better Gold Boots");
        add("item.evolvedmekanism.better_gold_chestplate", "Better Gold Chestplate");
        add("item.evolvedmekanism.better_gold_helmet", "Better Gold Helmet");
        add("item.evolvedmekanism.better_gold_hoe", "Better Gold Hoe");
        add("item.evolvedmekanism.better_gold_leggings", "Better Gold Leggings");
        add("item.evolvedmekanism.better_gold_paxel", "Better Gold Paxel");
        add("item.evolvedmekanism.better_gold_pickaxe", "Better Gold Pickaxe");
        add("item.evolvedmekanism.better_gold_shield", "Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.black", "Black Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.blue", "Blue Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.brown", "Brown Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.cyan", "Cyan Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.gray", "Gray Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.green", "Green Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.light_blue", "Light Blue Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.light_gray", "Light Gray Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.lime", "Lime Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.magenta", "Magenta Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.orange", "Orange Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.pink", "Pink Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.purple", "Purple Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.red", "Red Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.white", "White Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shield.yellow", "Yellow Better Gold Shield");
        add("item.evolvedmekanism.better_gold_shovel", "Better Gold Shovel");
        add("item.evolvedmekanism.better_gold_sword", "Better Gold Sword");
        add("item.evolvedmekanism.plaslitherite_axe", "Plaslitherite Axe");
        add("item.evolvedmekanism.plaslitherite_boots", "Plaslitherite Boots");
        add("item.evolvedmekanism.plaslitherite_chestplate", "Plaslitherite Chestplate");
        add("item.evolvedmekanism.plaslitherite_helmet", "Plaslitherite Helmet");
        add("item.evolvedmekanism.plaslitherite_hoe", "Plaslitherite Hoe");
        add("item.evolvedmekanism.plaslitherite_leggings", "Plaslitherite Leggings");
        add("item.evolvedmekanism.plaslitherite_paxel", "Plaslitherite Paxel");
        add("item.evolvedmekanism.plaslitherite_pickaxe", "Plaslitherite Pickaxe");
        add("item.evolvedmekanism.plaslitherite_shield", "Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.black", "Black Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.blue", "Blue Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.brown", "Brown Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.cyan", "Cyan Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.gray", "Gray Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.green", "Green Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.light_blue", "Light Blue Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.light_gray", "Light Gray Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.lime", "Lime Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.magenta", "Magenta Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.orange", "Orange Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.pink", "Pink Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.purple", "Purple Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.red", "Red Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.white", "White Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shield.yellow", "Yellow Plaslitherite Shield");
        add("item.evolvedmekanism.plaslitherite_shovel", "Plaslitherite Shovel");
        add("item.evolvedmekanism.plaslitherite_sword", "Plaslitherite Sword");
        add("item.evolvedmekanism.refined_redstone_axe", "Refined Redstone Axe");
        add("item.evolvedmekanism.refined_redstone_boots", "Refined Redstone Boots");
        add("item.evolvedmekanism.refined_redstone_chestplate", "Refined Redstone Chestplate");
        add("item.evolvedmekanism.refined_redstone_helmet", "Refined Redstone Helmet");
        add("item.evolvedmekanism.refined_redstone_hoe", "Refined Redstone Hoe");
        add("item.evolvedmekanism.refined_redstone_leggings", "Refined Redstone Leggings");
        add("item.evolvedmekanism.refined_redstone_paxel", "Refined Redstone Paxel");
        add("item.evolvedmekanism.refined_redstone_pickaxe", "Refined Redstone Pickaxe");
        add("item.evolvedmekanism.refined_redstone_shield", "Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.black", "Black Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.blue", "Blue Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.brown", "Brown Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.cyan", "Cyan Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.gray", "Gray Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.green", "Green Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.light_blue", "Light Blue Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.light_gray", "Light Gray Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.lime", "Lime Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.magenta", "Magenta Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.orange", "Orange Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.pink", "Pink Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.purple", "Purple Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.red", "Red Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.white", "White Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shield.yellow", "Yellow Refined Redstone Shield");
        add("item.evolvedmekanism.refined_redstone_shovel", "Refined Redstone Shovel");
        add("item.evolvedmekanism.refined_redstone_sword", "Refined Redstone Sword");
        add("item.evolvedmekanism.noctis_rozuli_axe", "Noctis Rozuli Axe");
        add("item.evolvedmekanism.noctis_rozuli_boots", "Noctis Rozuli Boots");
        add("item.evolvedmekanism.noctis_rozuli_chestplate", "Noctis Rozuli Chestplate");
        add("item.evolvedmekanism.noctis_rozuli_helmet", "Noctis Rozuli Helmet");
        add("item.evolvedmekanism.noctis_rozuli_hoe", "Noctis Rozuli Hoe");
        add("item.evolvedmekanism.noctis_rozuli_leggings", "Noctis Rozuli Leggings");
        add("item.evolvedmekanism.noctis_rozuli_paxel", "Noctis Rozuli Paxel");
        add("item.evolvedmekanism.noctis_rozuli_pickaxe", "Noctis Rozuli Pickaxe");
        add("item.evolvedmekanism.noctis_rozuli_shield", "Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.black", "Black Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.blue", "Blue Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.brown", "Brown Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.cyan", "Cyan Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.gray", "Gray Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.green", "Green Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.light_blue", "Light Blue Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.light_gray", "Light Gray Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.lime", "Lime Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.magenta", "Magenta Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.orange", "Orange Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.pink", "Pink Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.purple", "Purple Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.red", "Red Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.white", "White Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shield.yellow", "Yellow Noctis Rozuli Shield");
        add("item.evolvedmekanism.noctis_rozuli_shovel", "Noctis Rozuli Shovel");
        add("item.evolvedmekanism.noctis_rozuli_sword", "Noctis Rozuli Sword");
        add("apt.evolvedmekanism.invalid_supercharging", "Couldn't form, invalid Supercharging Element arrangement.");
    }
}
