package fr.iglee42.evolvedmekanism.registries;

import java.util.function.UnaryOperator;

import fr.iglee42.evolvedmekanism.EvolvedMekanism;
import mekanism.common.ChemicalConstants;
import mekanism.common.Mekanism;
import mekanism.common.item.ItemNutritionalPasteBucket;
import mekanism.common.registration.impl.FluidDeferredRegister;
import mekanism.common.registration.impl.FluidDeferredRegister.MekanismFluidType;
import mekanism.common.registration.impl.FluidRegistryObject;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraftforge.fluids.ForgeFlowingFluid.Flowing;
import net.minecraftforge.fluids.ForgeFlowingFluid.Source;

public class EMFluids {

    private EMFluids() {
    }

    public static final FluidDeferredRegister FLUIDS = new FluidDeferredRegister(EvolvedMekanism.MODID);

    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_COPPER = registerMolten("copper",0xFFC15A36);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_AMETHYST = registerMolten("amethyst",0xFFB38EF3);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_COAL = registerMolten("coal",0xFF2E2E2E);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_DIAMOND = registerMolten("diamond",0xFF4AEDD9);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_EMERALD = registerMolten("emerald",0xFF17DD62);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENDER = registerMolten("ender",0xFF0B4D42);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BLAZE = registerMolten("blaze",0xFFFFC100);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CLAY = registerMolten("clay",0xFFA1A7B1);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GLASS = registerMolten("glass",0xFFD0EAE9);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_REDSTONE = registerMolten("redstone",0xFFFF0000);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_OBSIDIAN = registerMolten("obsidian",0xFF271E3D);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_QUARTZ = registerMolten("quartz",0xFFDDD4C6);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SLIME = registerMolten("slime",0xFF8CD782);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SOUL = registerMolten("soul",0xFF6A5244);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ALUMINUM = registerMolten("aluminum",0xFFAEF0CB);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BRASS = registerMolten("brass",0xFFFBCC68);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BRONZE = registerMolten("bronze",0xFFFFBF74);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_COBALT = registerMolten("cobalt",0xFF4475AE);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CONSTANTAN = registerMolten("constantan",0xFFEFC163);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ELECTRUM = registerMolten("electrum",0xFFFFFF86);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENDERIUM = registerMolten("enderium",0xFF1D7E8C);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GOLD = registerMolten("gold",0xFFFDF55F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_HEPATIZON = registerMolten("hepatizon",0xFF5F486A);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_INVAR = registerMolten("invar",0xFFA3B1A8);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_IRON = registerMolten("iron",0xFFFDF55F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_KNIGHTSLIME = registerMolten("knightslime",0xFFF9B0F7);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LEAD = registerMolten("lead",0xFF8CA7A3);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LUMIUM = registerMolten("lumium",0xFFFFF1AA);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_MANYULLYN = registerMolten("manyullyn",0xFF9261CC);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_NETHERITE = registerMolten("netherite",0xFF5A575A);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_NICKEL = registerMolten("nickel",0xFFE7D498);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_OSMIUM = registerMolten("osmium",0xFFCEE3F1);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PEWTER = registerMolten("pewter",0xFFA1A097);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PIG_IRON = registerMolten("pig_iron",0xFFF0A8A4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PLATINUM = registerMolten("platinum",0xFF87C2C8);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_QUEENS_SLIME = registerMolten("queens_slime",0xFF38994D);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_REFINED_GLOWSTONE = registerMolten("refined_glowstone",0xFFFFF4AC);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_REFINED_OBSIDIAN = registerMolten("refined_obsidian",0xFF9B82BA);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ROSE_GOLD = registerMolten("rose_gold",0xFFFC7C63);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SIGNALUM = registerMolten("signalum",0xFFFB6114);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SILICON_BRONZE = registerMolten("silicon_bronze",0xFF736C6F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SILVER = registerMolten("silver",0xFF9FADB4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SLIMESTEEL = registerMolten("slimesteel",0xFFB9F7F7);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SOULSTEEL = registerMolten("soulsteel",0xFF6A5244);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_STEEL = registerMolten("steel",0xFF9F9B99);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TIN = registerMolten("tin",0xFFF8FAFC);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TUNGSTEN = registerMolten("tungsten",0xFF5A655E);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_URANIUM = registerMolten("uranium",0xFFB1FAB3);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ZINC = registerMolten("zinc",0xFFB9E9C1);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_VERIDIUM = registerMolten("veridium",0xFF5885CD);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GRAVITITE = registerMolten("gravitite",0xFFE370C3);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_STRATUS = registerMolten("stratus",0xFFE6ABE0);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_DESH = registerMolten("desh",0xFFD68D4D);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_OSTRUM = registerMolten("ostrum",0xFFA86C73);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CALORITE = registerMolten("calorite",0xFFCB4E4F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_JUPERIUM = registerMolten("juperium",0xFFB6E3FF);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SATURLYTE = registerMolten("saturlyte",0xFFA932E7);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_NEPTUNIUM = registerMolten("neptunium",0xFF82A86C);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_RADIUM = registerMolten("radium",0xFF8BFF8D);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PLUTONIUM = registerMolten("plutonium",0xFFFFF500);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ELECTROLYTE = registerMolten("electrolyte",0xFF2215CA);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BLUTONIUM = registerMolten("blutonium",0xFF3A81D8);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CYANITE = registerMolten("cyanite",0xFF4CC6E8);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GRAPHITE = registerMolten("graphite",0xFF1E1A21);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LUDICRITE = registerMolten("ludicrite",0xFFE744C9);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_HELLFORGED = registerMolten("hellforged",0xFFA4E2D7);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_MANASTEEL = registerMolten("manasteel",0xFF67B9EE);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TERRASTEEL = registerMolten("terrasteel",0xFF6AE862);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ELEMENTIUM = registerMolten("elementium",0xFFE084A5);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ALFSTEEL = registerMolten("alfsteel",0xFFFFB500);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GAIASTEEL = registerMolten("gaiasteel",0xFFE56166);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_COPPER_ALLOY = registerMolten("copper_alloy",0xFFC89A3F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENERGETIC_ALLOY = registerMolten("energetic_alloy",0xFFFACE6A);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_VIBRANT_ALLOY = registerMolten("vibrant_alloy",0xFFE9FE77);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_REDSTONE_ALLOY = registerMolten("redstone_alloy",0xFFF95C5C);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CONDUCTIVE_ALLOY = registerMolten("conductive_alloy",0xFFE56166);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PULSATING_ALLOY = registerMolten("pulsating_alloy",0xFF9CEEAF);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_DARK_STEEL = registerMolten("dark_steel",0xFF888888);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SOULARIUM = registerMolten("soularium",0xFF6D5B35);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_END_STEEL = registerMolten("end_steel",0xFFCFC97D);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PINK_SLIME = registerMolten("pink_slime",0xFFE7CAE2);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BETTER_GOLD = registerMolten("better_gold",0xFFFCF046);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PLASLITHERITE = registerMolten("plaslitherite",0xFF626869);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PROSPERITY = registerMolten("prosperity",0xFFE0FEFE);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SOULIUM = registerMolten("soulium",0xFF8C563C);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_INFERIUM = registerMolten("inferium",0xFF94B200);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PRUDENTIUM = registerMolten("prudentium",0xFF00AD1A);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TERTIUM = registerMolten("tertium",0xFFD84800);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_IMPERIUM = registerMolten("imperium",0xFF0085DD);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SUPREMIUM = registerMolten("supremium",0xFFD30000);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_AWAKENED_SUPREMIUM = registerMolten("awakened_supremium",0xFFD37B00);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_INSANIUM = registerMolten("insanium",0xFF7100B2);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ORNIUM = registerMolten("ornium",0xFF442655);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LIGHTIUM = registerMolten("lightium",0xFF8CB0CA);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TORNIUM = registerMolten("tornium",0xFF4E4E4E);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_OURANIUM = registerMolten("ouranium",0xFF264E55);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_INFUSED_IRON = registerMolten("infused_iron",0xFF2EAF37);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TAINTED_GOLD = registerMolten("tainted_gold",0xFFCA7328);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LITHIUM = registerMolten("lithium",0xFFC6B6AA);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_THORIUM = registerMolten("thorium",0xFF33337F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_MAGNESIUM = registerMolten("magnesium",0xFFD8B3D4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_NEUTRONIUM = registerMolten("neutronium",0xFF1B1625);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_TITANIUM = registerMolten("titanium",0xFF88737F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_MANGANESE = registerMolten("manganese",0xFFB7BCF1);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_IRIDIUM = registerMolten("iridium",0xFFC2B4C2);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BORON = registerMolten("boron",0xFF616165);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_IESNIUM = registerMolten("iesnium",0xFF94D4DB);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ORATCHALCUM = registerMolten("oratchalcum",0xFFCEC285);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_PRISMALIUM = registerMolten("prismalium",0xFFA4D1C2);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_MELODIUM = registerMolten("melodium",0xFFFFCAE4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_STELLARIUM = registerMolten("stellarium",0xFFCBD6D6);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_FLUX = registerMolten("flux",0xFFF7E16B);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_DRACONIUM = registerMolten("draconium",0xFF986AC4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_AWAKENED_DRACONIUM = registerMolten("awakened_draconium",0xFFFF9C00);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_BLACK_IRON = registerMolten("black_iron",0xFF585858);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_REDSTONE_INGOT = registerMolten("redstone_ingot",0xFFAA0F01);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENHANCED_REDSTONE_INGOT = registerMolten("enhanced_redstone_ingot",0xFFAA4701);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENDER_INGOT = registerMolten("ender_ingot",0xFF1B7B6B);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ENHANCED_ENDER_INGOT = registerMolten("enhanced_ender_ingot",0xFF117382);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CRYSTALTINE = registerMolten("crystaltine",0xFF9CDFFC);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_THE_ULTIMATE = registerMolten("the_ultimate",0xFFF6F6F6);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_INFINITY = registerMolten("infinity",0xFF6DCFF9);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CHORIUM = registerMolten("chorium",0xFFA47CA4);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SENTRITE = registerMolten("sentrite",0xFF747477);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_COMPRESSED_IRON = registerMolten("compressed_iron",0xFF66625E);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_NETHER_STAR = registerMolten("nether_star",0xFFCBD6D6);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_CERTUS_QUARTZ = registerMolten("certus_quartz",0xFFBADBFF);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_FLUIX = registerMolten("fluix",0xFFC090F7);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_SKYJADE = registerMolten("skyjade",0xFF8AB754);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_AMBROSIUM = registerMolten("ambrosium",0xFFF1EF5F);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_ZANITE = registerMolten("zanite",0xFF7635DD);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_LAPIS = registerMolten("lapis",0xFF13408B);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_GLOWSTONE = registerMolten("glowstone",0xFFE5AC44);
    public static final FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> MOLTEN_DEBRIS = registerMolten("debris",0xFF5C332B);


    private static FluidRegistryObject<MekanismFluidType, Source, Flowing, LiquidBlock, BucketItem> registerMolten(String name,int color){
        return FLUIDS.register("molten_" + name, properties -> properties.tint(color).texture(EvolvedMekanism.rl("block/molten_still"),EvolvedMekanism.rl("block/molten_flowing")).renderOverlay(EvolvedMekanism.rl("block/molten_still")));
    }
}